[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_ENV = "production"

[context.production.environment]
  NODE_ENV = "production"

[context.production]
  command = "apt-get update && apt-get install -y libgl1-mesa-dev && npm run build"
