[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20.17.0"

[build.lifecycle]
  onBuildCommandStart = "apt-get update && apt-get install -y libgl1-mesa-dev"
